### PR TITLE
OvmfPkg/PlatformPei: Use fw_cfg for platform id

### PR DESCRIPTION
**Pull request by mcastelino**
Firmware (and OS) today uses the device id of the host bridge
as a means of determining the platform on which it is running.
Use fw_cfg if available instead obtain this information. This
will allow it to be decoupled from PCI (as it should be) in the
case of a virtual platform.

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by mcastelino** [comment]
@rbradford This change did not introduce the regression. virt reboot failed once we registered the machine type as a PCIe machine (as it should be).  From what it looks like reboot/shutdown has been broken in Q35+OVMF for a while. In the case of virt the kernel panic is due a page fault on pcie MMIO access. 

https://github.com/intel/nemu/issues/120

**Comment by rbradford** [comment]
@mcastelino I understand by "regression" I guess I meant started to cause tests to fail. We don't want to have failing tests as then when we land further changes we won't have confidence.

I also realised i'd never tagged the previous commit on #2 so that also had not been through NEMU Jenkins. I'm going to add support to the NEMU CI for running with HEAD of this repo so that we can verify updates of both OVMF and NEMU together.

**Comment by rbradford** [comment]
@mcastelino I can confirm that it was #2 that was that the problematic change rather than this one. With intel/nemu#122 it will be possible to test OVMF changes.

As such I rolled out the commit in #2. So it is now in this PR.

**Comment by mcastelino** [comment]
@rbradford thanks. I will remove the PCIe change and limit this PR to just the fw_cfg changes till I find the right way to solve the PCIe memory read issue and why we see kernel page faults and panics on this access. It looks like the PCIe MCFG space is not mapped when the efi shutdown/reboot code runs.

Forcing a legacy access hides this issue. https://github.com/mcastelino/edk2/commit/3f87ae80285047c5e4195dd797fee6e150091974

**Comment by rbradford** [comment]
Tested with no NEMU changes: https://nemu-jenkins-ci.westus2.cloudapp.azure.com/job/nemu/job/PR-126/1/consoleFull

Tested combined with NEMU change in intel/nemu#119 https://nemu-jenkins-ci.westus2.cloudapp.azure.com/job/nemu/job/PR-126/2/consoleFull

And it looks good.

**Pull request merged**
